#theme: jekyll-theme-midnight
theme: minima
#name: moneybbq.com
title: moneybbq.com
repository: pjh68/pjh68.github.io

minima:
  date_format: "%d %B %Y"

header_pages:
  - projects.md
  - contribute.md
  - about.md

twitter_username: pjh68
github_username: pjh68
stackoverflow_username: pjh68


show_excerpts: true

collections:
  projects:
    output: true

plugins:
  - jekyll-feed

feed:
  excerpt_only: true
